FROM mcr.microsoft.com/dotnet/sdk:6.0
WORKDIR /app
COPY ./FastVlangVisualization/FastVlangVisualization.csproj FastVlangVisualization.csproj
RUN dotnet restore FastVlangVisualization.csproj
COPY . .
RUN dotnet publish -c Release -o /output --no-restore --nologo
